version: "3.8"

services:
  postgres:
    container_name: pg_database
    image: "postgres:12.4-alpine"
    networks:
      - dev
    ports:
      - "${PG_PORT}:5432"
    restart: always
    volumes:
      - "pg-data:/var/lib/postgresql/data"
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
      PG_DATA: /var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    networks:
      - dev
    ports:
      - "7070:8080"
  mongo:
    image: "mongo:4.4.1-bionic"
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - "mongo-data:/data/db"
      - "mongo-configdb:/data/configdb"
  mongo-express:
    image: "mongo-express"
    restart: always
    ports:
      - "7071:8081"

networks:
  dev:
volumes:
  pg-data:
  mongo-data:
  mongo-configdb: